#!/usr/bin/env bash
# script that configures a subdomain

sub_check () {
	input=$(dig "$2"."$1" | grep -A1 "ANSWER SECTION:" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $input" | awk '{print "The subname " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
	sub_check "$1" "www"
	sub_check "$1" "lb-01"
	sub_check "$1" "web-01"
	sub_check "$1" "web-02"
elif [ "$#" == 2 ]; then
	sub_check "$1" "$2"
fi
