#!/usr/bin/env bash
# script that transfers a file from client to server
# args:
#	path of file to be transferred
#	IP address of the server
#	username to connect with
#	path to ssh private key

if [[ $# -lt 4 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3"@"$2":~
fi
