#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header
# Add HAProxy PPA and install HAProxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.7
sudo apt-get -y update
sudo apt-get -y install haproxy=2.7.\*

# configure the load balancer
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

sudo sed -i -e '$a\listen firstbalance\n\tbind *:80\n\tbalance roundrobin\n\toption forwardfor\n\toption httpchk\n\tserver 73349-web-01 52.91.132.254:80 check\n\tserver 73349-web-02 100.25.203.14:80 check\n'

sudo service haproxy restart
