#!/usr/bin/env bash
# script that creates a compressed mysqldum file as backup
# dump file is sent to a remote server in another physical
# location. 

sudo mysqldump -uroot -p "$1" --all-databaases > backup.sql
tar -cvzf  "$(date + %d-%m-%Y).tar.gz" backup.sql
