#!/usr/bin/env bash
# prints 1-100
# prints fizzbuzz for multiples of both 3 and 5
# prints fizz for multiples of 3
# prints buzz for multiples of 5

for (( i=1; i<=100; i++ ))
do
	if (("$i % 3 == 0" && "$i % 5 == 0")) ; then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ] ; then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ] ; then
		echo "Buzz"
	else
		echo "$i"
	fi
done
