#!/usr/bin/env bash
# script prints information about a file

filename="school"
if [ -e $filename ] ; then
	echo "$filename file exists"
	if [ -s $filename ] ; then
		echo "$filename is not empty"
	else echo "$filename is empty"
	fi
	if [ -f $filename ] ; then
		echo "$filename is a regular file"
	fi
else echo "$filename file does not exist"
fi
