#!/usr/bin/env bash
# script prints information about a file

filename="./school"
if [ -e $filename ] ; then
	echo "school file exists"
	if [ -s $filename ] ; then
		echo "school is not empty"
	else echo "school is empty"
	fi
	if [ -f $filename ] ; then
		echo "school is a regular file"
	fi
else echo "school file does not exist"
fi
